FROM    alpine:3.12.0
COPY    bot/requirements.txt /bot/requirements.txt

RUN apk --no-cache upgrade && \
    apk --no-cache add python3 py3-pip py3-cryptography python3-dev gcc libc-dev zlib && \
    pip3 install --no-cache-dir -r /bot/requirements.txt

COPY bot/main.py /bot/main.py

ENTRYPOINT ["python3", "-u", "/bot/main.py"]
